# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=810'] # Our expected results files are fairly large
    - id: no-commit-to-branch # Work in branches please -- not in main
      args: ['--branch', 'main']
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--target-version", "py310"]
        exclude: ^tests/end_to_end_expected
-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.6
    hooks:
      - id: djlint-django
        args: ['--reformat', '--lint']
-   repo: local
    hooks:
      - id: check-absent-migrations
        name: Check absent migrations with manage.py makemigrations --check --dry-run
        entry: poetry run sh -c './manage.py makemigrations --check --dry-run --settings=config.settings.local'
        pass_filenames: false
        language: system
        always_run: true
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^cpmonitor/static/.*$
        types_or: [css, scss, javascript]

# - repo: https://github.com/RobertCraigie/pyright-python
  # rev: v1.1.292
  # hooks:
  # - id: pyright
