# Bind to HTTP port to allow local development without reverse proxy.
services:
  djangoapp:
    user: "1000"
  nginx-unprivileged:
    ports:
      - 80:8080

networks:
  nginx_network:
    name: local_nginx_network
    driver: bridge
    external: false