version: '3'

services:
  djangoapp:
    container_name: djangoapp
    build: .
    volumes:
      - ./:/db
      - static_volume:/static
      - image_volume:/images
      - nginx_config_volume:/nginx/conf.d
    networks:
      - nginx_network
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:?Please select an environment using '--env-file .env.local' or '--env-file .env.production' (see README.md)!}
      - SECRET_KEY=${SECRET_KEY:?Please set the secret key environment variable.}

  nginx-unprivileged:
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - 80:8001
    volumes:
      - nginx_config_volume:/etc/nginx/conf.d
      - static_volume:/cpmonitor/static
      - image_volume:/cpmonitor/images
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  # just declare the volumes so nginx and django can share them
  nginx_config_volume:
  static_volume:
  image_volume:
