version: '3'

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /home/monitoring/ssl_certificates:/etc/letsencrypt
    networks:
      - production
      - testing
      - reverse_proxy_network
    depends_on:
      - acme-sh

  acme-sh:
    image: neilpang/acme.sh
    container_name: acme-sh
    command: daemon
    volumes:
      - /home/monitoring/ssl_certificates:/acme.sh
    networks:
      - reverse_proxy_network

networks:
  production:
    external:
      name: production_nginx_network
  testing:
    external:
      name: testing_nginx_network
  reverse_proxy_network:
    driver: bridge