# Generated by Django 4.1.6 on 2023-02-25 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("zipcode", models.CharField(max_length=5, verbose_name="PLZ")),
                ("url", models.URLField(blank=True, verbose_name="Homepage")),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="Einleitung"),
                ),
                (
                    "budget",
                    models.IntegerField(
                        default=0, verbose_name="CO2 Budget [Mio Tonnen]"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
                (
                    "planned_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geplanter Start"
                    ),
                ),
                (
                    "planned_completion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geplantes Ende"
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Suggested"),
                            (2, "Planned"),
                            (3, "Waiting"),
                            (4, "In Progress"),
                            (5, "Delayed"),
                            (6, "Succeeded"),
                            (7, "Failed"),
                            (8, "Rejected"),
                        ],
                        default=0,
                        verbose_name="Zustand",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, default="", verbose_name="Begründung Zustand"
                    ),
                ),
                (
                    "completion",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Vervollständigungsgrad",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cpmonitor.city",
                        verbose_name="Stadt",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
