# Generated by Django 4.1.7 on 2023-03-05 16:19

from django.db import migrations
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="introduction",
            field=martor.models.MartorField(blank=True, verbose_name="Einleitung"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=martor.models.MartorField(
                blank=True, default="", verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="justification",
            field=martor.models.MartorField(
                blank=True, default="", verbose_name="Begründung Zustand"
            ),
        ),
    ]
