# Generated by Django 4.1.7 on 2023-03-13 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0002_alter_city_introduction_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Kommune", "verbose_name_plural": "Kommunen"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Sektor / Maßnahme",
                "verbose_name_plural": "Sektoren und Maßnahmen",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="assessment_action_plan",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Eine einleitende Übersicht in die Bewertung des Klimaaktionsplans der Kommune.</p>\n            <p>Hier könnt Ihr zusammenfassen, was ihr als Ganzes von dem Plan haltet.</p>\n            <p>Auf Sektorebene und bis zu den einzelnen Maßnahmen könnt Ihr weiter Details ergänzen.</p>",
                verbose_name="Bewertung Klimaaktionsplan",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="assessment_administration",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Wie bewertet ihr die Nachhaltigkeitsarchitektur der Verwaltung?</p>\n            <p>Die Checkliste hilft dabei, die Übersicht zu behalten.\n            Es ist noch nicht klar, ob die Checkliste selber so angezeigt werden kann.\n            Dieser Text sollte sie also zusammenfassen.</p>\n            <p>Derzeit findest Du die Checkliste nur in der Master Struktur.</p>\n        ",
                verbose_name="Bewertung Verwaltung",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="assessment_status",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Eine einleitende Übersicht in die Bewertung des Umsetzungsstandes.</p>\n            <p>Hält die Kommune sich im Wesentlichen an ihren eigenen Plan?</p>\n            <p>Auf Sektorebene und bis zu den einzelnen Maßnahmen könnt Ihr weiter Details ergänzen.</p>",
                verbose_name="Bewertung Umsetzungsstand",
            ),
        ),
        migrations.RenameField(
            model_name="city",
            old_name="budget",
            new_name="co2e_budget",
        ),
        migrations.AlterField(
            model_name="city",
            name="co2e_budget",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Derzeit nicht genutzt.",
                verbose_name="CO2e Budget [Mio Tonnen]",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="E-Mail Adresse, über die das Lokalteam erreicht werden kann.",
                max_length=254,
                verbose_name="Kontakt E-Mail",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="contact_name",
            field=models.CharField(
                blank=True,
                help_text="Name des Lokalteams oder einer Ansprechperson aus dem Lokalteam, das dieses Monitoring betreibt.",
                max_length=255,
                verbose_name="Kontakt Name",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="last_update",
            field=models.DateField(auto_now=True, verbose_name="Letzte Aktualisierung"),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_completion",
            field=models.DateField(
                blank=True,
                help_text="Nur falls bekannt.",
                null=True,
                verbose_name="Tatsächlicher Ende",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="actual_start",
            field=models.DateField(
                blank=True,
                help_text="Nur falls bekannt.",
                null=True,
                verbose_name="Tatsächlicher Start",
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="state",
            new_name="execution_assessment",
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_assessment",
            field=models.IntegerField(
                choices=[
                    (0, "unbekannt (grau)"),
                    (1, "vor dem Plan (grün)"),
                    (2, "im Plan (grün)"),
                    (3, "zurückgestellt / verzögert (orange)"),
                    (4, "nicht ausreichend / in Teilen gescheitert (rot)"),
                    (5, "gescheitert (rot)"),
                    (6, "fehlt im Plan (rot)"),
                ],
                default=0,
                help_text='\n            <p>Bei Maßnahmen: Wird/wurde die Maßnahme wie geplant umgesetzt?</p>\n            <p>Bei Sektoren / Maßnahmengruppen:</p>\n            <p>Wenn hier "unbekannt" ausgewählt wird, werden die Umsetzungsstände der Maßnahmen in diesem Sektor / dieser Gruppe zusammengefasst.</p>\n            <p>Bei anderen Auswahlen wird diese Zusammenfassung überschrieben. Das sollte nur passieren, wenn sie unpassend oder irreführend ist.</p>\n        ',
                verbose_name="Bewertung des Umsetzungsstandes",
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="completion",
            new_name="execution_completion",
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_completion",
            field=models.IntegerField(
                blank=True,
                help_text="\n            <p>Bei wenigen Maßnahmen ist es möglich den Fortschritt quantitativ einzugeben. Nur bei solchen sollte hier ein Wert eingegeben werden.</p>\n            <p>Ob und wie diese Zahlen angezeigt werden, ist noch unklar.</p>\n        ",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Vervollständigungsgrad in Prozent",
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="justification",
            new_name="execution_justification",
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_justification",
            field=models.TextField(
                blank=True,
                help_text="Die Auswahl bei der Bewertung kann hier ausführlich begründet werden.",
                verbose_name="Begründung der Bewertung",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="execution_progress",
            field=models.IntegerField(
                choices=[
                    (0, "unbekannt"),
                    (1, "ungeplant"),
                    (2, "in Zukunft geplant"),
                    (3, "läuft"),
                    (4, "abgeschlossen / gescheitert"),
                ],
                default=2,
                help_text="\n            <p>Eine grobe Einteilung, wo sich diese Maßnahme zeitlich in der Planung befindet.</p>\n            <p>Dies kann z.B. genutzt werden, um Maßnahmen zu filtern, deren Umsetzungsstand noch nicht bewertet werden kann.</p>\n        ",
                verbose_name="Fortschritt",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="plan_assessment",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Würde(n) die im Klimaaktionsplan beschriebenen Maßnahme(n) ausreichen, um das gesteckte Ziel zu erreichen?</p>\n            <p>Sollte das gesteckte Ziel nicht ausreichen, kann das auch hier beschrieben werden.</p>\n        ",
                verbose_name="Bewertung der Planung",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="responsible_organ",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Genauer Name des verantwortlichen Gremiums oder der verantwortlichen Behörde.</p>\n            <p>Möglichst mit Ansprechperson, Kontaktdaten und was sonst notwendig ist, um Informationen einzuholen.</p>\n            <p>Diese Informationen könnten später in separate Felder aufgeteilt werden.</p>\n        ",
                verbose_name="Verantwortliches Organ",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Kann Beschreibung, Bewertung und Unsetzungsstand enthalten</p>\n            <p>Kann in einer Übersicht meherer Sektoren / Maßnahmen dargestellt werden.</p>\n            <p>Deswegen möglichst kurz und ohne Formatierungen. Fett, Kursiv, Links, etc. sind okay.</p>\n        ",
                verbose_name="Kurztext",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="introduction",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Eine kurze Beschreibung der Situation in der Kommune.</p>\n            <p>Kann in einer Übersicht aller Kommunen dargestellt werden.</p>\n            <p>Deswegen möglichst kurz und ohne Formatierungen. Fett, Kursiv, Links, etc. sind okay.</p>\n        ",
                verbose_name="Einleitung",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="city",
            field=models.ForeignKey(
                help_text="\n            <p>Bitte nicht ändern!</p>\n            <p>Derzeit könnten dann die Strukturen der Klimaaktionspläne der Städte gehörig durcheinander geraten.</p>\n            <p>Wir arbeiten noch an der Lösung, das zu verhindern.</p>\n        ",
                on_delete=django.db.models.deletion.PROTECT,
                to="cpmonitor.city",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Texte aus dem Klimaaktionsplan können hier eins-zu-eins eingegeben werden.</p>\n            <p>Für Sektoren und Maßnahmengruppen sind Einleitungstexte aus dem Plan geeignet.</p>\n            <p>Für Maßnahmen sollte hier die genaue Beschreibung stehen.</p>\n        ",
                verbose_name="Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="planned_completion",
            field=models.DateField(
                blank=True,
                help_text="Nur falls im Klimaaktionsplan angegeben.",
                null=True,
                verbose_name="Geplantes Ende",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="planned_start",
            field=models.DateField(
                blank=True,
                help_text="Nur falls im Klimaaktionsplan angegeben.",
                null=True,
                verbose_name="Geplanter Start",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="\n            <p>Überschrift des Sektors, der Maßnahmengruppe oder der Maßnahme.</p>\n            <p>Möglichst wie im Klimaaktionsplan angegeben.</p>\n        ",
                max_length=255,
                verbose_name="Titel",
            ),
        ),
    ]
