# Generated by Django 4.1.7 on 2023-03-13 15:43
# manually extended

from django.db import migrations, models
from django.utils.text import slugify

from cpmonitor.models import Task as CurrentTask


def add_city_slug(apps, schema_editor):
    City = apps.get_model("cpmonitor", "City")
    db_alias = schema_editor.connection.alias
    print("")
    for city in City.objects.using(db_alias).all():
        city.slug = slugify(city.name)
        print(
            "Changed slug of %(name)s to %(slug)s."
            % {"name": city.name, "slug": city.slug}
        )
        city.save()


def _get_ancestors(Model, db_alias, obj, steplen):
    """Essentially a copy of treebeard.mp_tree.MP_Node.get_ancestors."""
    if obj.depth == 1:
        return Model.objects.none()
    paths = [obj.path[0:pos] for pos in range(0, len(obj.path), steplen)[1:]]
    return Model.objects.using(db_alias).filter(path__in=paths).order_by("depth")


def add_task_slugs(apps, schema_editor):
    Task = apps.get_model("cpmonitor", "Task")
    db_alias = schema_editor.connection.alias
    print("")
    for task in Task.objects.using(db_alias).all():
        task.slugs = ""
        for anc in _get_ancestors(Task, db_alias, task, 4):
            task.slugs += slugify(anc.title) + "/"
        task.slugs += slugify(task.title)
        print(
            "Changed slugs of %(title)s to %(slugs)s."
            % {"title": task.title, "slugs": task.slugs}
        )
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0003_alter_city_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                default="asdf",
                max_length=255,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_city_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                editable=False,
                unique=True,
                max_length=255,
                verbose_name="slug",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="slugs",
            field=models.SlugField(
                default="asdf",
                max_length=255,
                verbose_name="slugs",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_task_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="slugs",
            field=models.SlugField(
                editable=False,
                unique=True,
                max_length=255,
                verbose_name="slugs",
            ),
        ),
    ]
