# Generated by Django 4.1.7 on 2023-03-13 15:43

from django.db import migrations, models
from django.utils.text import slugify


def add_city_slug(apps, schema_editor):
    City = apps.get_model("cpmonitor", "City")
    db_alias = schema_editor.connection.alias
    print("")
    for city in City.objects.using(db_alias).all():
        city.slug = slugify(city.name)
        print(f"Changed slug of {city.name} to {city.slug}.")
        city.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0003_alter_city_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                default="asdf",
                error_messages={
                    "unique": "Der Name ist schon vergeben. Verwende bitte eine eindeutige Ergänzung."
                },
                max_length=255,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_city_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                unique=True,
                error_messages={
                    "unique": "Der Name ist schon vergeben. Verwende bitte eine eindeutige Ergänzung."
                },
                max_length=255,
                verbose_name="slug",
            ),
        ),
    ]
