# Generated by Django 4.1.7 on 2023-03-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0005_alter_task_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cpmonitor.city"
            ),
        ),
    ]
