# Generated by Django 4.1.7 on 2023-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0007_rename_to_execution_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="execution_status",
            field=models.IntegerField(
                choices=[
                    (0, "unbekannt"),
                    (2, "in Arbeit"),
                    (4, "abgeschlossen"),
                    (6, "verzögert / fehlt"),
                    (8, "gescheitert"),
                ],
                default=0,
                help_text='\n            <p>Bei Maßnahmen: Wird/wurde die Maßnahme wie geplant umgesetzt?</p>\n            <dl>\n                <dt>unbekannt</dt><dd><ul>\n                    <li>Keine Infos vorhanden</li>\n                    <li>Es gibt einen unkonkreten Beschluss</li>\n                </ul></dd>\n                <dt>in Arbeit</dt><dd><ul>\n                    <li>Finden wir erstmal gut: Dinge werden bearbeitet.</li>\n                    <li>Maßnahmen, die im Zeitplan sind (sowohl begonnen als auch in Planung).</li>\n                    <li>Maßnahmen die in Umsetzung sind.</li>\n                    <li>Maßnahmen für die es einen positiven Beschluss + Zeitplan (Konkretisierung) gibt.</li>\n                </ul></dd>\n                <dt>abgeschlossen</dt><dd><ul>\n                    <li>Top und im Plan fertig.</li>\n                </ul></dd>\n                <dt>verzögert / fehlt</dt><dd><ul>\n                    <li>Maßnahmen, die nicht im Zeitplan sind.</li>\n                    <li>Maßnahmen, die im Prinzip noch vervollständigt werden können.</li>\n                    <li>Maßnahmen, die im KAP nicht aufgeführt sind, (und nicht bearbeitet weden)</li>\n                    <li>Im Prinzip könnten sie aber noch angegangen werden.</li>\n                </ul></dd>\n                <dt>gescheitert</dt><dd><ul>\n                    <li>Kann niemals mehr geschafft werden (Eiche ist gefällt, Moor ist mit einer Autobahn überbaut)</li>\n                    <li>Sowohl für Maßnahmen aus dem KAP, als auch Dinge, die gar nich im KAP aufgeführt waren.</li>\n                </ul></dd>\n            </dl>\n            <p>Bei Sektoren / Maßnahmengruppen:</p>\n            <p>Wenn hier "unbekannt" ausgewählt wird, werden die Umsetzungsstände der Maßnahmen in diesem Sektor / dieser Gruppe zusammengefasst.</p>\n            <p>Bei anderen Auswahlen wird diese Zusammenfassung überschrieben. Das sollte nur passieren, wenn sie unpassend oder irreführend ist.</p>\n        ',
                verbose_name="Umsetzungsstand",
            ),
        ),
    ]
