# Generated by Django 4.1.7 on 2023-04-20 14:28

from django.db import migrations, models

from ..models import Task


def correct_slugs(apps, schema_editor):
    for task in Task.objects.all():
        # task.slugs = Task._get_slugs_with_parent(task.get_parent(), task.title)
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0009_alter_task_slugs_task_unique_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slugs",
            field=models.SlugField(
                editable=False, max_length=255, verbose_name="In der URL"
            ),
        ),
        migrations.RunPython(correct_slugs, migrations.RunPython.noop),
    ]
