# Generated by Django 4.1.7 on 2023-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0010_alter_task_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="resolution_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Datum des Klimaneutralitäts-Beschlusses",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="target_year",
            field=models.IntegerField(
                blank=True,
                help_text="z.B. 2035",
                null=True,
                verbose_name="Zieljahr Klimaneutralität",
            ),
        ),
    ]
