# Generated by Django 4.1.7 on 2023-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0011_city_resolution_date_city_target_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_field",
                    models.CharField(max_length=255, verbose_name="Test Feld"),
                ),
            ],
        ),
    ]
