# Generated by Django 4.1.7 on 2023-05-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0011_city_resolution_date_city_target_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="Bilddatei"
                    ),
                ),
                (
                    "alt_description",
                    models.CharField(
                        max_length=255,
                        verbose_name="Beschreibung (für Menschen, die das Bild nicht sehen können)",
                    ),
                ),
                ("source", models.CharField(max_length=255, verbose_name="Quelle")),
                ("license", models.CharField(max_length=255, verbose_name="Lizenz")),
                ("caption", models.TextField(verbose_name="Bildunterschrift")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_charts",
                        to="cpmonitor.city",
                    ),
                ),
            ],
            options={
                "verbose_name": " KPI Graph",
                "verbose_name_plural": "KPI Graphen",
            },
        ),
    ]
