# Generated by Django 4.1.7 on 2023-05-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0012_chart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chart",
            options={"verbose_name": "Diagramm", "verbose_name_plural": "Diagramme"},
        ),
        migrations.AlterField(
            model_name="chart",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="cpmonitor.city",
            ),
        ),
    ]
