# Generated by Django 4.1.7 on 2023-05-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0013_alter_chart_options_alter_chart_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistClimateActionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "climate_action_plan_exists",
                    models.BooleanField(
                        default=False, verbose_name="Gibt es einen KAP?"
                    ),
                ),
                (
                    "target_date_exists",
                    models.BooleanField(
                        default=False,
                        verbose_name="Ist im KAP ein Zieljahr der Klimaneutralität hinterlegt und wurde das vom höchsten kommunalen Gremium beschlossen?",
                    ),
                ),
                (
                    "based_on_remaining_co2_budget",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sind die Einsparziele im KAP auf Grundlage des Restbudgets berechnet?",
                    ),
                ),
                (
                    "sectors_of_climate_vision_used",
                    models.BooleanField(
                        default=False,
                        verbose_name="Bilanziert der KAP in den Sektoren der Klimavision (inkl. LULUCF und Landwirtschaft)",
                    ),
                ),
                (
                    "scenario_for_climate_neutrality_till_2035_exists",
                    models.BooleanField(
                        default=False,
                        verbose_name="Enthält der KAP ein Szenario mit dem Ziel Klimaneutralität bis 2035?",
                    ),
                ),
                (
                    "scenario_for_business_as_usual_exists",
                    models.BooleanField(
                        default=False,
                        verbose_name="Ist ein Trendszenario hinterlegt (wie entwickeln sich die THG-Emissionen, wenn alles so weiterläuft wie bisher)?",
                    ),
                ),
                (
                    "annual_costs_are_specified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sind die jährlichen Kosten und der jährliche Personalbedarf der Maßnahmen ausgewiesen?",
                    ),
                ),
                (
                    "tasks_are_planned_yearly",
                    models.BooleanField(
                        default=False,
                        verbose_name="Haben die Maßnahmen eine jahresscharfe Planung?",
                    ),
                ),
                (
                    "tasks_have_responsible_entity",
                    models.BooleanField(
                        default=False,
                        verbose_name="Sind verantwortliche Personen/Fachbereiche/kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
                    ),
                ),
                (
                    "annual_reduction_of_emissions_can_be_predicted",
                    models.BooleanField(
                        default=False,
                        verbose_name="Wird anhand der Maßnahmen ein jährlicher Reduktionspfad des Energiebedarfs und der THG-Emissionen ersichtlich?",
                    ),
                ),
                (
                    "concept_for_participation_specified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Gibt es ein gutes Konzept zur Akteur:innenbeteiligung?",
                    ),
                ),
                (
                    "sustainability_architecture_in_administration_exists",
                    models.BooleanField(
                        default=False,
                        verbose_name="Gibt es eine gute Nachhaltigkeitsarchitektur in der Verwaltung?",
                    ),
                ),
                (
                    "climate_council_exists",
                    models.BooleanField(
                        default=False,
                        verbose_name="Gibt es einen Klimabeirat/Klimarat/Bürger:innenrat?",
                    ),
                ),
                (
                    "KAP Checkliste",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checklist_climate_action_plan",
                        to="cpmonitor.city",
                    ),
                ),
            ],
        ),
    ]
