# Generated by Django 4.1.7 on 2023-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0017_administrationchecklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capchecklist",
            name="cap_exists",
        ),
    ]
