# Generated by Django 4.1.7 on 2023-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0017_administrationchecklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="draft_mode",
            field=models.BooleanField(
                default=True,
                help_text="Im Entwurfs-Modus wird ist die Kommune für normale Besucher im Frontend unsichtbar. Nur wenn im gleichen Browser ein User im Admin angemeldet ist, wird sie angezeigt.",
                verbose_name="Entwurfs-Modus",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="draft_mode",
            field=models.BooleanField(
                default=True,
                help_text="Im Entwurfs-Modus wird ist der Sektor/die Maßnahme für normale Besucher im Frontend unsichtbar. Nur wenn im gleichen Browser ein User im Admin angemeldet ist, wird er/sie angezeigt.",
                verbose_name="Entwurfs-Modus",
            ),
        ),
    ]
