# Generated by Django 4.1.7 on 2023-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0018_city_draft_mode_task_draft_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                help_text="\n            <p>Name der Kommune. Maximal 50 Zeichen.</p>\n        ",
                max_length=50,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="introduction",
            field=models.CharField(
                blank=True,
                help_text="\n            <p>Eine kurze Beschreibung der Situation in der Kommune. Maximal 200 Zeichen. Keine Formatierungen.</p>\n            <p>Kann in einer Übersicht aller Kommunen oder als Vorschau eines Links dargestellt werden.</p>\n        ",
                max_length=200,
                verbose_name="Teaser",
            ),
        ),
        migrations.RenameField(
            model_name="city",
            old_name="introduction",
            new_name="teaser",
        ),
        migrations.AddField(
            model_name="city",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Ein einleitender Text, der die wesentlichen Inhalte zusammenfasst und/oder einen Überblick über die weiteren Inhalte gibt.</p>\n            <p>Dieser wird nur auf der Seite der Kommune angezeigt unter einem fett gedruckten Absatz, der den Teaser enthält.</p>\n        ",
                verbose_name="Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="\n            <p>Überschrift des Sektors / der Maßnahme.</p>\n            <p>Wie im Klimaaktionsplan angegeben oder verkürzt. Maximal 50 Zeichen.</p>\n        ",
                max_length=50,
                verbose_name="Titel",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="summary",
            field=models.CharField(
                blank=True,
                help_text="\n            <p>Eine kurze Beschreibung des Sektors / der Maßnahme. Maximal 200 Zeichen. Keine Formatierungen.</p>\n            <p>Kann in einer Übersicht mehrerer Sektoren / Maßnahmen oder als Vorschau eines Links dargestellt werden.</p>\n        ",
                max_length=200,
                verbose_name="Teaser",
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="summary",
            new_name="teaser",
        ),
    ]
