# Generated by Django 4.1.7 on 2023-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0019_alter_city_introduction_alter_city_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="internal_information",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Interne Informationen, Notizen, Referenzen etc.</p>\n            <p>Die hier angegebenen Informationen werden nur in der Admin-Oberfläche angezeigt und nicht im Frontend.</p>\n        ",
                verbose_name="Interne Informationen",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="internal_information",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Interne Informationen, Notizen, Referenzen etc.</p>\n            <p>Die hier angegebenen Informationen werden nur in der Admin-Oberfläche angezeigt und nicht im Frontend.</p>\n        ",
                verbose_name="Interne Informationen",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="internal_information",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Interne Informationen, Notizen, Referenzen etc.</p>\n            <p>Die hier angegebenen Informationen werden nur in der Admin-Oberfläche angezeigt und nicht im Frontend.</p>\n        ",
                verbose_name="Interne Informationen",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="actual_completion",
            field=models.DateField(
                blank=True,
                help_text="Nur falls bekannt.",
                null=True,
                verbose_name="Tatsächliches Ende",
            ),
        ),
    ]
