# Generated by Django 4.1.7 on 2023-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0019_alter_city_introduction_alter_city_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="draft_mode",
            field=models.BooleanField(
                default=True,
                help_text="Im Entwurfs-Modus ist die Kommune für normale Besucher im Frontend unsichtbar. Nur wenn im gleichen Browser ein User im Admin angemeldet ist, wird sie angezeigt.",
                verbose_name="Entwurfs-Modus",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="draft_mode",
            field=models.BooleanField(
                default=True,
                help_text="Im Entwurfs-Modus ist der Sektor/die Maßnahme für normale Besucher im Frontend unsichtbar. Nur wenn im gleichen Browser ein User im Admin angemeldet ist, wird er/sie angezeigt.",
                verbose_name="Entwurfs-Modus",
            ),
        ),
    ]
