# Generated by Django 4.1.7 on 2023-06-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0020_alter_city_draft_mode_alter_task_draft_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charts",
                to="cpmonitor.city",
            ),
        ),
        migrations.CreateModel(
            name="LocalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="\n            <p>Offizieller Name der Lokalgruppe. Maximal 100 Zeichen.</p>\n        ",
                        max_length=100,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="\n            <p>URL der Website der Lokalgruppe.</p>\n        ",
                    ),
                ),
                (
                    "teaser",
                    models.CharField(
                        blank=True,
                        help_text="\n            <p>Eine kurze Beschreibung der Lokalgruppe. Maximal 200 Zeichen. Keine Formatierungen.</p>\n        ",
                        max_length=200,
                        verbose_name="Teaser",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="\n            <p>Details über die Lokalgruppe. Sollte mindestens eine Kontaktmöglichkeit enthalten sowie\n            Angaben darüber, wie die Gruppe das Monitoring durchführt (Datenquellen? Gesprächspartner?\n            Als Geschichte erzählt). Mögliche weitere Infos (sofern das nicht alles ohnehin schon\n            auf der Website der Gruppe steht):</p>\n            <ul>\n            <li>Ehrenamtliche, Aktuelle Zahl, Zur Verfügung stehende Zeit. (Ziel: Erwartungsmanagement)</li>\n            <li>Beteiligungsmöglichkeiten</li>\n            <li>ggf. Hintergrund zum Klimaaktionsplan? Wie war unser Weg dahin?</li>\n            </ul>\n        ",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        upload_to="uploads/local_groups",
                        verbose_name="Bild der Lokalgruppe",
                    ),
                ),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="local_group",
                        to="cpmonitor.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokalgruppe",
                "verbose_name_plural": "Lokalgruppen",
            },
        ),
    ]
