# Generated by Django 4.1.7 on 2023-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0022_chart_internal_information_city_internal_information_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="frontpage",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Die Maßahme soll auf der Startseite angezeigt werden, um sie besonders"
                    " hervorzuheben. Dies funktioniert nur für Maßnahmen und nicht für"
                    " Handlungsfelder, also nur, wenn es keine weiteren Untermaßnahmen mehr gibt."
                ),
                verbose_name="Startseite",
            ),
        ),
    ]
