# Generated by Django 4.1.7 on 2023-08-01 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cpmonitor", "0025_alter_task_responsible_organ_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="city_admins",
            field=models.ManyToManyField(
                blank=True,
                help_text='\n            <p>Diese Benutzer können zusätzlich andere Benutzter als Admins und Bearbeiter eintragen.</p>\n            <p>Sie brauchen nicht als "Bearbeiter" eingetragen zu werden.</p>\n        ',
                related_name="administered_cities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kommunen Admins",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="city_editors",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n            <p>Diese Benutzer können alle Inhalte der Kommune bearbeiten.</p>\n        ",
                related_name="edited_cities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kommunen Bearbeiter",
            ),
        ),
    ]
