# Generated by Django 4.1.7 on 2023-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0025_alter_task_responsible_organ_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_protection_management_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein Klimaschutzmanagement? Ist dieses befugt, Entscheidungen zu treffen? Sind Haushaltsmittel hinterlegt?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_protection_monitoring_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein Monitoring von Kimaschutzmaßnahmen?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_protection_reports_are_continuously_published_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Werden regelmäßige Klimaschutz- und Energieberichte veröffentlicht?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_relevance_check_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Klimarelevanzprüfung: werden alle Beschlüsse von Verwaltung und Politik auf die Auswirkungen auf das Klima geprüft?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_technical_committee_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es einen Fachausschuss mit dem Fokus auf Klimaschutz? Ist dieser befugt, Haushaltsentscheidungen zu treffen?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="guidelines_for_sustainable_procurement_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es Richtlinien für ein nachhaltiges Beschaffungswesen?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="interdisciplinary_climate_protection_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Ist Klimaschutz als Querschnittsaufgabe über alle Fachbereiche etabliert?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="intersectoral_concepts_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es (sektorenübergreifende) Konzepte (siehe Planung und Konzepte bzw. Sektorenübergreifende Konzepte)?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="municipal_office_for_funding_management_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es eine eigene Kommunale Stelle für Fördermittelmanagement (unter anderem  Beantragung etc. für den Klimaschutz)?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="public_relation_with_local_actors_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Vernetzung in der Öffentlichkeitsarbeit mit lokalen Akteuren (Handwerk, Sparkasse...)?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="annual_costs_are_specified_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind die jährlichen Kosten und der jährliche Personalbedarf der Maßnahmen ausgewiesen?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="annual_reduction_of_emissions_can_be_predicted_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Wird anhand der Maßnahmen ein jährlicher Reduktionspfad des Energiebedarfs und der THG-Emissionen ersichtlich?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="based_on_remaining_co2_budget_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind die Einsparziele im KAP auf Grundlage des Restbudgets berechnet?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="cap_exists_rationale",
            field=models.TextField(
                blank=True, verbose_name="Begründung zu: Gibt es einen KAP?"
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="climate_council_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es einen Klimabeirat/Klimarat/Bürger:innenrat?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="concept_for_participation_specified_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein gutes Konzept zur Akteur:innenbeteiligung?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="scenario_for_business_as_usual_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Ist ein Trendszenario hinterlegt (wie entwickeln sich die THG-Emissionen, wenn alles so weiterläuft wie bisher)?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="scenario_for_climate_neutrality_till_2035_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Enthält der KAP ein Szenario mit dem Ziel Klimaneutralität bis 2035?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Bilanziert der KAP in den Sektoren der Klimavision (inkl. LULUCF und Landwirtschaft)?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="sustainability_architecture_in_administration_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es eine gute Nachhaltigkeitsarchitektur in der Verwaltung?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="target_date_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Ist im KAP ein Zieljahr der Klimaneutralität hinterlegt und wurde das vom höchsten kommunalen Gremium beschlossen?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="tasks_are_planned_yearly_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Haben die Maßnahmen eine jahresscharfe Planung?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind verantwortliche Personen/Fachbereiche/kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used",
            field=models.BooleanField(
                default=False,
                verbose_name="Bilanziert der KAP in den Sektoren der Klimavision (inkl. LULUCF und Landwirtschaft)?",
            ),
        ),
    ]
