# Generated by Django 4.1.7 on 2023-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0025_alter_task_responsible_organ_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Handlungsfeld / Maßnahme",
                "verbose_name_plural": "Handlungsfelder und Maßnahmen",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="assessment_action_plan",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Eine einleitende Übersicht in die Bewertung des Klimaaktionsplans der Kommune.</p>\n            <p>Hier könnt Ihr zusammenfassen, was ihr als Ganzes von dem Plan haltet.</p>\n            <p>Auf Handlungsfelderebene und bis zu den einzelnen Maßnahmen könnt Ihr weiter Details ergänzen.</p>",
                verbose_name="Bewertung Klimaaktionsplan",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="assessment_status",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Eine einleitende Übersicht in die Bewertung des Umsetzungsstandes.</p>\n            <p>Hält die Kommune sich im Wesentlichen an ihren eigenen Plan?</p>\n            <p>Auf Handlungsfelderebene und bis zu den einzelnen Maßnahmen könnt Ihr weiter Details ergänzen.</p>",
                verbose_name="Bewertung Umsetzungsstand",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="\n            <p>Texte aus dem Klimaaktionsplan können hier eins-zu-eins eingegeben werden.</p>\n            <p>Für Handlungsfelder sind Einleitungstexte aus dem Plan geeignet.</p>\n            <p>Für Maßnahmen sollte hier die genaue Beschreibung stehen.</p>\n        ",
                verbose_name="Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="draft_mode",
            field=models.BooleanField(
                default=True,
                help_text="Im Entwurfs-Modus ist das Handlungsfeld/die Maßnahme für normale Besucher im Frontend unsichtbar. Nur wenn im gleichen Browser ein User im Admin angemeldet ist, wird er/sie angezeigt.",
                verbose_name="Entwurfs-Modus",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="execution_status",
            field=models.IntegerField(
                choices=[
                    (0, "unbekannt"),
                    (2, "in Arbeit"),
                    (4, "abgeschlossen"),
                    (6, "verzögert / fehlt"),
                    (8, "gescheitert"),
                ],
                default=0,
                help_text='\n            <p>Bei Maßnahmen: Wird/wurde die Maßnahme wie geplant umgesetzt?</p>\n            <dl>\n                <dt>unbekannt</dt><dd><ul>\n                    <li>Keine Infos vorhanden</li>\n                    <li>Es gibt einen unkonkreten Beschluss</li>\n                </ul></dd>\n                <dt>in Arbeit</dt><dd><ul>\n                    <li>Finden wir erstmal gut: Dinge werden bearbeitet.</li>\n                    <li>Maßnahmen, die im Zeitplan sind (sowohl begonnen als auch in Planung).</li>\n                    <li>Maßnahmen die in Umsetzung sind.</li>\n                    <li>Maßnahmen für die es einen positiven Beschluss + Zeitplan (Konkretisierung) gibt.</li>\n                </ul></dd>\n                <dt>abgeschlossen</dt><dd><ul>\n                    <li>Top und im Plan fertig.</li>\n                </ul></dd>\n                <dt>verzögert / fehlt</dt><dd><ul>\n                    <li>Maßnahmen, die nicht im Zeitplan sind.</li>\n                    <li>Maßnahmen, die im Prinzip noch vervollständigt werden können.</li>\n                    <li>Maßnahmen, die im KAP nicht aufgeführt sind, (und nicht bearbeitet weden)</li>\n                    <li>Im Prinzip könnten sie aber noch angegangen werden.</li>\n                </ul></dd>\n                <dt>gescheitert</dt><dd><ul>\n                    <li>Kann niemals mehr geschafft werden (Eiche ist gefällt, Moor ist mit einer Autobahn überbaut)</li>\n                    <li>Sowohl für Maßnahmen aus dem KAP, als auch Dinge, die gar nich im KAP aufgeführt waren.</li>\n                </ul></dd>\n            </dl>\n            <p>Bei Handlungsfeldern:</p>\n            <p>Wenn hier "unbekannt" ausgewählt wird, werden die Umsetzungsstände der Maßnahmen in diesem Handlungsfeld zusammengefasst.</p>\n            <p>Bei anderen Auswahlen wird diese Zusammenfassung überschrieben. Das sollte nur passieren, wenn sie unpassend oder irreführend ist.</p>\n        ',
                verbose_name="Umsetzungsstand",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="teaser",
            field=models.CharField(
                blank=True,
                help_text="\n            <p>Eine kurze Beschreibung des Handlungsfelds / der Maßnahme. Maximal 200 Zeichen. Keine Formatierungen.</p>\n            <p>Kann in einer Übersicht mehrerer Handlungsfelder / Maßnahmen oder als Vorschau eines Links dargestellt werden.</p>\n        ",
                max_length=200,
                verbose_name="Teaser",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="\n            <p>Überschrift des Handlungsfelds / der Maßnahme.</p>\n            <p>Wie im Klimaaktionsplan angegeben oder verkürzt. Maximal 50 Zeichen.</p>\n        ",
                max_length=50,
                verbose_name="Titel",
            ),
        ),
    ]
