# Generated by Django 4.1.7 on 2023-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0028_alter_task_options_alter_city_assessment_action_plan_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrationchecklist",
            name="climate_protection_reports_are_continuously_published",
        ),
        migrations.RemoveField(
            model_name="administrationchecklist",
            name="climate_technical_committee_exists",
        ),
        migrations.RemoveField(
            model_name="administrationchecklist",
            name="interdisciplinary_climate_protection_exists",
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_management_exists",
            field=models.BooleanField(
                default=False,
                help_text="Klimaschutzmanager:innen können von der Nationalen Initiative für Klimaschutz (NKI) gefördert werden. Allerdings ist wichtig, dass das Klimaschutzmanagement an einer Stelle in der Verwaltung angesiedelt ist wo es Entscheidungen treffen und möglichst frei agieren kann sowie über finanzielle Mittel verfügt.",
                verbose_name="Gibt es ein Klimaschutzmanagement, das befugt ist, Entscheidungen zu treffen und über Haushaltsmittel verfügt?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_monitoring_exists",
            field=models.BooleanField(
                default=False,
                help_text="Monitoring bedeutet ein Überwachen / Überblick über den Erfolg von Klimaschutzmaßnahmen. Dieser kann in eingespaarten Emissionen sichtbar gemacht werden und ist wichtig um das Ziel der Klimaneutralität und notwendige Schritte im Auge zu behalten.",
                verbose_name="Gibt es ein Monitoring von Kimaschutzmaßnahmen?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_relevance_check_exists",
            field=models.BooleanField(
                default=False,
                help_text="Aufgrund der enormen Dringlichkeit von Klimaschutzmaßnahmen zur Bekämpfung der Klimakrise, ist es wesentlich alle kommunalen Beschlüsse hinsichtlich ihrer Verträglichkeit mit Klimaschutz zu bewerten. Dies erfolgt durch eine Integration eines „Klima-Checks“ / Klimarelevanzprüfung / Klimaschutzrelevanzprüfung in jegliche Beschlussvorlage: Beschlüsse werden somit bereits während der Erstellung durch die Fachbereiche auf ihre Klimarelevanz hin (vor-)bewertet und Aspekte des Klimaschutzes sind automatisch integraler Bestandteil jeder Beschlussfassung. Klimafolgen werden somit transparent. Langfristig baut die Kommune Kompetenzen auf, um die Auswirkung auf das Klima bei allen relevanten Entscheidungen zu berücksichtigen.",
                verbose_name="Klimarelevanzprüfung: werden alle Beschlüsse von Verwaltung und Politik auf die Auswirkungen auf das Klima geprüft?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="guidelines_for_sustainable_procurement_exists",
            field=models.BooleanField(
                default=False,
                help_text="Die Kommunalverwaltung kann aufgrund ihres großen Beschaffungsvolumens mit ihrer Nachfrage energieeffiziente Produkte fördern und damit einen wichtigen Beitrag zum Klimaschutz leisten. Wichtig ist, möglichst nur Produkte und Dienstleistungen zu erwerben, die wirklich benötigt werden und im Sinne der Nachhaltigkeit neben einer hohen Umweltverträglichkeit auch sozialen wie ökonomischen Aspekten entsprechen. Umweltfreundliche Beschaffung sollte in grundlegenden Dokumenten der Behörde wie dem eigenen Leitbild, verpflichtenden Dienstanweisungen oder einem Beschaffungsleitfaden als Organisationsziel definiert werden.",
                verbose_name="Gibt es Richtlinien für ein nachhaltiges Beschaffungswesen?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="intersectoral_concepts_exists",
            field=models.BooleanField(
                default=False,
                help_text="Sektorenübergreifende Konzepte umfassen unter anderem Klimaanpassungs- Quatierskonzepte, die Klimaschutzaspekte über mehrere Sektoren hinweg in der Kommune verankern sollen. Es werden also Energieerzeugung, Mobilität, Wärmeversorung etc. mitbedacht.\nPlanungspapiere sind unter anderem Bauleitplanungen, Flächennutzungspläne, Wärmeleitplanung etc. Auch hier soll sichergestellt werden, dass Klimaschutz in Bauvorhaben zukünftig umgesetzt wird z.B. in der Form von ausgeschriebenen Windeigungsflächen, Festlegung von klimaneutraler Fernwärmenutzung etc.",
                verbose_name="Beziehen (sektorenübergreifende) Konzepte und Planungspapiere die Klimaschutz mit ein?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="municipal_office_for_funding_management_exists",
            field=models.BooleanField(
                default=False,
                help_text="Beantragung für Fördermittel ist oft sehr zeitintensiv, und somit werden für Klimaschutz notwendige personelle Kapazitäten oft hierauf verwendet. Eigene Stellen sollen Entlastung schaffen und dafür sorgen, dass effizient an Klimaschutz gearbeitet werden kann.",
                verbose_name="Gibt es eine eigene Kommunale Stelle für Fördermittelmanagement (unter anderem Beantragung etc. für den Klimaschutz)?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="public_relation_with_local_actors_exists",
            field=models.BooleanField(
                default=False,
                help_text="Mit Klimabeirat/Klimarat/Bürger:innenrat sind Gremien gemeint, die aus Betroffenen / Bürgerperspektive die Lokalpolitik beraten. Um politischen Einfluss auszuüben sollten diese regelmäßig tagen.",
                verbose_name="Gibt es einen Klimabeirat/Klimarat/Bürger:innenrat? Ist so ein Gremium in der Kommune eingerichtet und tagt regelmäßig?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_costs_are_specified",
            field=models.BooleanField(
                default=False,
                help_text="Die jährlichen Kosten für Maßnahmen, sowie Kosten für den Personalbedarf für die Umsetzung dieser sollen den Aufwand einschätzbar machen und Sicherheit für die Planung der Umsetzung liefern.",
                verbose_name="Sind die jährlichen Kosten und der jährliche Personalbedarf der Maßnahmen ausgewiesen?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_reduction_of_emissions_can_be_predicted",
            field=models.BooleanField(
                default=False,
                help_text="Aus dem genauen Zeitplan der Maßnahmenplanung kann ab jetzt bis zum Jahr der Klimaneutralität (2030/35) die THG-Emissionen und der Endenergiebedarf jährlich prognostiziert werden in allen Sektoren. Wird z.B. ein Braunkohlewerk im Jahr X geschlossen, sinken die Emissionen um Y. Dadurch wird der Weg zur Treibhausgasneutralität klar erkennbar und zu kompensierende Emissionen sichtbar.",
                verbose_name="Wird anhand der Maßnahmen ein jährlicher Reduktionspfad des Energiebedarfs und der THG-Emissionen ersichtlich?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="based_on_remaining_co2_budget",
            field=models.BooleanField(
                default=False,
                help_text="Das Restbudget beschreibt das globale Kontingent an Treibhausgasen (THG), das für die Einhaltung des Pariser Klimaabkommens zukünftig noch emittiert werden kann. Dieses THG-Kontingent kann auf einzelne Nationen und wiederum auf Kommunen heruntergebrochen werden. Die Kommune kann dies als Richtwert nutzen, den es nicht zu überschreiten gilt.",
                verbose_name="Sind die Einsparziele im Klima-Aktionsplan auf Grundlage des Restbudgets berechnet?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="cap_exists",
            field=models.BooleanField(
                default=False,
                help_text="Ein Klima-Aktionsplan (auch KAP/Klimaschutzkonzept/integriertes Klimaschutzkonzept) ist ein von einer Kommune beschlossener Plan/Konzept, in dem beispielhaft oder auch in mehreren Szenarien festgelegt ist, wie die Kommune bis 2035 / 20XX klimaneutral wird. Dieses Ziel der Klimaneutralität wird auf Maßnahmen zur Erreichung heruntergebrochen. Dabei ist nicht nur Emissionsreduktion sondern die Erreichung der Klimaneutralität in allen Bereichen der Kommune von Bedeutung.",
                verbose_name="Gibt es einen Klima-Aktionsplan?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="concept_for_participation_specified",
            field=models.BooleanField(
                default=False,
                help_text="Alle Akteur:innen in einer Kommune sollten bei der Erstellung / Umsetzung eines KAPs beteiligt werden. Unterschiedliche Akteur:innen der Kommune sind: Bürger:innen (z.B. LocalZero-Teams), Verwaltung der Kommune, höchste politische Gremien der Kommune, Stakeholder:innen in der Kommune (z.B. kommunale Unternehmen oder Vereine)",
                verbose_name="Gibt es ein gutes Konzept zur Akteur:innenbeteiligung?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_business_as_usual_exists",
            field=models.BooleanField(
                default=False,
                help_text="Ein Trendszenario ist ein Szenario, welches die Treibhausgas-Emissionen der Kommune in den Folgejahren darstellt. Dieses soll die Notwendigkeit des Handelns deutlich machen und Erfolge bei der Umsetzung und damit einhergehenden Reduktion von Emissionen sichtbar machen.",
                verbose_name="Ist ein Trendszenario hinterlegt?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_climate_neutrality_till_2035_exists",
            field=models.BooleanField(
                default=False,
                help_text="Das Szenario soll zeigen wie die Kommune unter realistischen Bedinungen (politischer Entwicklung, Dauer der Maßnahmen etc.) ihre Emissionen auf Netto-Null reduzieren kann, oder wie weit eine Reduktion realistisch aber ambitioniert möglich ist.",
                verbose_name="Enthält der Klima-Aktionsplan ein Szenario mit dem Ziel Klimaneutralität bis 2035?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used",
            field=models.BooleanField(
                default=False,
                help_text="Die Klimavision beinhaltet die Sektoren Strom, Wärme, Verkehr, Industrie, Gebäude, Abfall, Landwirtschaft, LULUCF (Landnutzung, Landnutzungsänderungen und Forstwirtschaft). Die letzten 3 sind besonders selten in KAPs enthalten, nichtsdestotrotz wichtig für die Bilanz der Kommune.",
                verbose_name="Bilanziert der Klima-Aktionsplan in den Sektoren der Klimavision?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="target_date_exists",
            field=models.BooleanField(
                default=False,
                help_text="Dies sorgt dafür, dass nicht nur Emissionen gemindert werden, sondern, ein klares Ziel bis z.B. 2035 gesetzt wird bis wann die Kommune möglichst ohne Kompensation klimaneutral (keine Emissionen vom Gebiet der Gemeinde) werden soll.\nMit höchstes Gremium ist hier gemeint z.B. der Stadtrat oder Gemeinderat.",
                verbose_name="Ist im KAP ein Zieljahr der Klimaneutralität hinterlegt, das vom höchsten kommunalen Gremium beschlossen wurde?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_are_planned_yearly",
            field=models.BooleanField(
                default=False,
                help_text="Eine genaue Planung der Fertigstellung der Maßnahmen ist die Grundvoraussetzung, um den Erfolg / Fortschritt der Umsetzung des Klima-Aktionsplans zu messen.",
                verbose_name="Haben die Maßnahmen eine jahresscharfe Planung?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity",
            field=models.BooleanField(
                default=False,
                help_text="Ohne klar verteilte Verantwortlichkeiten können Maßnahmen nicht umgesetzt werden. Die Verantwortlichen können sowohl in der Kommunalverwaltung (z.B. Abteilungen) oder außerhalb (z.B. Stadtwerke) sein.",
                verbose_name="Sind verantwortliche Personen/Fachbereiche/kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
            ),
        ),
    ]
