# Generated by Django 4.1.7 on 2023-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0029_remove_administrationchecklist_climate_protection_reports_are_continuously_published_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_protection_management_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein Klimaschutzmanagement, das befugt ist, Entscheidungen zu treffen und über Haushaltsmittel verfügt?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_protection_monitoring_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein Monitoring von Kimaschutzmaßnahmen?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="climate_relevance_check_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Klimarelevanzprüfung: werden alle Beschlüsse von Verwaltung und Politik auf die Auswirkungen auf das Klima geprüft?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="guidelines_for_sustainable_procurement_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es Richtlinien für ein nachhaltiges Beschaffungswesen?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="intersectoral_concepts_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Beziehen (sektorenübergreifende) Konzepte und Planungspapiere die Klimaschutz mit ein?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="municipal_office_for_funding_management_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es eine eigene Kommunale Stelle für Fördermittelmanagement (unter anderem Beantragung etc. für den Klimaschutz)?",
            ),
        ),
        migrations.AddField(
            model_name="administrationchecklist",
            name="public_relation_with_local_actors_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es einen Klimabeirat/Klimarat/Bürger:innenrat? Ist so ein Gremium in der Kommune eingerichtet und tagt regelmäßig?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="annual_costs_are_specified_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind die jährlichen Kosten und der jährliche Personalbedarf der Maßnahmen ausgewiesen?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="annual_reduction_of_emissions_can_be_predicted_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Wird anhand der Maßnahmen ein jährlicher Reduktionspfad des Energiebedarfs und der THG-Emissionen ersichtlich?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="based_on_remaining_co2_budget_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind die Einsparziele im Klima-Aktionsplan auf Grundlage des Restbudgets berechnet?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="cap_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es einen Klima-Aktionsplan?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="concept_for_participation_specified_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Gibt es ein gutes Konzept zur Akteur:innenbeteiligung?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="scenario_for_business_as_usual_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Ist ein Trendszenario hinterlegt?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="scenario_for_climate_neutrality_till_2035_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Enthält der Klima-Aktionsplan ein Szenario mit dem Ziel Klimaneutralität bis 2035?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Bilanziert der Klima-Aktionsplan in den Sektoren der Klimavision?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="target_date_exists_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Ist im Klima-Aktionsplan ein Zieljahr der Klimaneutralität hinterlegt, das vom höchsten kommunalen Gremium beschlossen wurde?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="tasks_are_planned_yearly_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Haben die Maßnahmen eine jahresscharfe Planung?",
            ),
        ),
        migrations.AddField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind verantwortliche Personen/Fachbereiche/kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
            ),
        ),
    ]
