# Generated by Django 4.2.7 on 2023-11-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0032_task_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_costs_are_specified",
            field=models.BooleanField(
                default=False,
                help_text="Die jährlichen Kosten für Maßnahmen, sowie Kosten für den Personalbedarf für die Umsetzung der Maßnahmen, machen den Aufwand einschätzbar und liefern Sicherheit für die Planung der Umsetzung.\n\nSind keine Kosten und keine Personalstellen hinterlegt sinkt die Wahrscheinlichkeit, dass die Politik diese Maßnahme schnell freigibt. Denn die Kosten und der nötige Personalumfang muss erst ermittelt werden.",
                verbose_name="Sind die jährlichen Kosten und der jährliche Personalbedarf der Maßnahmen ausgewiesen?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="based_on_remaining_co2_budget",
            field=models.BooleanField(
                default=False,
                help_text="Das Restbudget beschreibt das globale Kontingent an Treibhausgasen (THG), das für die Einhaltung des Pariser Klimaabkommens zukünftig noch emittiert werden kann. Dieses THG-Kontingent kann auf einzelne Nationen und wiederum auf Kommunen heruntergebrochen werden. Jede Kommune hat somit ein „persönliches kommunales Restbudget“, das sie für die Einhaltung des Pariser 1,5 Grad Zieles nicht überschreiten darf.",
                verbose_name="Sind die Einsparziele im Klima-Aktionsplan auf Grundlage des Restbudgets berechnet?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="cap_exists",
            field=models.BooleanField(
                default=False,
                help_text="Ein Klima-Aktionsplan (auch KAP / Klimaschutzkonzept / integriertes Klimaschutzkonzept) ist ein von einer Kommune beschlossener Plan/Konzept, in dem beispielhaft oder auch in mehreren Szenarien festgelegt ist, wie die Kommune bis 2035/20XX klimaneutral wird.\n\nIm ersten Teil des KAPs wird bilanziert: Wieviel Treibhausgase emittiert die Kommune derzeit?\n\nIm zweiten Teil des KAPs werden Maßnahmen aufgelistet, mit denen die Kommune klimaneutral werden kann. Dabei ist nicht nur Emissionsreduktion sondern die Erreichung der Klimaneutralität in allen Bereichen der Kommune von Bedeutung.",
                verbose_name="Gibt es einen Klima-Aktionsplan?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="concept_for_participation_specified",
            field=models.BooleanField(
                default=False,
                help_text="Alle Akteur:innen in einer Kommune sollten bei der Erstellung/Umsetzung eines KAPs beteiligt werden. Unterschiedliche Akteur:innen der Kommune sind: Bürger:innen (z.B. LocalZero-Teams), Verwaltung der Kommune, höchste politische Gremien der Kommune, Stakeholder:innen in der Kommune (z.B. kommunale Unternehmen oder Vereine).",
                verbose_name="Gibt es ein gutes Konzept zur Akteur:innenbeteiligung?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_business_as_usual_exists",
            field=models.BooleanField(
                default=False,
                help_text="Ein Trendszenario zeigt auf, wie sich die kommunalen Emissionen entwickeln, wenn die Kommune keine Maßnahmen in Richtung Klimaneutralität ergreift, also „business as usual“ betreibt. In diesem Fall können sich die kommunalen Emissionen trotzdem verändern, da bundespolitische Maßnahmen Einfluss auf kommunale Emissionen haben (Bsp: veränderter Bundesdeutscher Strommix).",
                verbose_name="Ist ein Trendszenario hinterlegt?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_climate_neutrality_till_2035_exists",
            field=models.BooleanField(
                default=False,
                help_text="Das Szenario soll zeigen wie die Kommune unter realistischen Bedinungen (politischer Entwicklung, Dauer der Maßnahmen etc.) ihre Emissionen auf Netto-Null reduzieren kann, oder wie weit eine Reduktion realistisch aber ambitioniert möglich ist.\n\nOft ist im KAP ein weiteres Szenario mit einem anderen Zieljahr hinterlegt zum Bsp. 2040 oder 2045",
                verbose_name="Enthält der Klima-Aktionsplan ein Szenario mit dem Ziel Klimaneutralität bis 2035?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used",
            field=models.BooleanField(
                default=False,
                help_text="Fast alle Kommunen führen ihre Treibhausgasbilanz mit BISKO (Bilanzierungs-Systematik Kommunal) durch. In dieser Systematik wird nur ein Teil der Industrie bilanziert, die Sektoren Abfall, Landwirtschaft und LULUCF fehlen völlig.\n\nDie Klimavision von LocalZero bilanziert die Sektoren Strom, Wärme, Verkehr, Industrie, Gebäude, Abfall, Landwirtschaft, LULUCF (Landnutzung, Landnutzungsänderungen und Forstwirtschaft).\n\nWenn die Kommune mit BISKO bilanziert ist es wichtig daraufhinzuweisen, dass die Bilanzierung ergänzt werden muss und vor allem in den fehlenden Sektoren trotzdem Maßnahmen entwickelt werden sollten.",
                verbose_name="Bilanziert der Klima-Aktionsplan in den Sektoren der Klimavision?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="target_date_exists",
            field=models.BooleanField(
                default=False,
                help_text="Die Jahreszahl (2035/20XX…) definiert, bis wann die Kommune – möglichst ohne Kompensation – klimaneutral werden will.\n\nDas bedeutet, dass allen Maßnahmen nachweisliche THG-Einsparmengen zugerechnet werden müssen, um dann als Ergebnis nachzuweisen, dass mit den geplanten Maßnahmen alle bilanzierten kommunalen THG-Emissionen eingespart werden.",
                verbose_name="Ist im Klima-Aktionsplan ein Zieljahr der Klimaneutralität hinterlegt, das vom höchsten kommunalen Gremium beschlossen wurde?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_are_planned_yearly",
            field=models.BooleanField(
                default=False,
                help_text="Eine genaue Planung der Maßnahmen ist eine Grundvoraussetzung, um den Erfolg/Fortschritt der Umsetzung des Klima-Aktionsplans zu messen. Optimal ist ein Ablaufplan, in dem die Reihenfolge und die zeitliche Überschneidung aller Maßnahmen genau aufgeschlüsselt ist.\n\nMit einem solchen Ablaufplan kann die Kommune die Reduktion der THG-Emissionen für jedes kommende Jahr prognostizieren und so nachweisen, dass sie das 1,5 Grad Ziel einhält.\n\nWichtig ist natürlich, dass zuerst die großen Emittenden auf Klimaneutralität umgestellt werden und danach bei den kleinen Emissionsquellen Maßnahmen ergriffen werden.",
                verbose_name="Haben die Maßnahmen eine jahresscharfe Planung?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity",
            field=models.BooleanField(
                default=False,
                help_text="Ohne klar verteilte Verantwortlichkeiten können Maßnahmen nicht umgesetzt werden. Die Verantwortlichen können sowohl in der Kommunalverwaltung (z.B. Abteilungen) oder außerhalb (z.B. Stadtwerke) sein. Bei jeder vorgeschlagenen Maßnahme sollte die zuständige Fachabteilung, die kommunale Tochter oder sogar die zuständige Sachbearbeitung genannt werden.",
                verbose_name="Sind verantwortliche Personen / Fachbereiche / kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity_rationale",
            field=models.TextField(
                blank=True,
                verbose_name="Begründung zu: Sind verantwortliche Personen / Fachbereiche / kommunale Gesellschaften für alle Maßnahmen hinterlegt?",
            ),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_reduction_of_emissions_can_be_predicted",
            field=models.BooleanField(
                default=False,
                help_text="Aus dem genauen Zeitplan der Maßnahmenplanung kann ab jetzt bis zum Jahr der Klimaneutralität (2035/20XX) die THG-Emissionen und der Endenergiebedarf jährlich prognostiziert werden in allen Sektoren. Wird z.B. ein Braunkohlewerk im Jahr X geschlossen, sinken die Emissionen um Y. Dadurch wird der Weg zur Treibhausgasneutralität klar erkennbar und zu kompensierende Emissionen sichtbar.",
                verbose_name="Wird anhand der Maßnahmen ein jährlicher Reduktionspfad des Energiebedarfs und der THG-Emissionen ersichtlich?",
            ),
        ),
    ]
