# Generated by Django 4.2.7 on 2023-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0033_alter_capchecklist_annual_costs_are_specified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_management_exists",
            field=models.BooleanField(
                default=False,
                help_text="Klimaschutzmanager:innen können von der Nationalen Initiative für Klimaschutz (NKI) gefördert werden. Allerdings ist wichtig, dass das Klimaschutzmanagement an einer Stelle in der Verwaltung angesiedelt ist, wo es Entscheidungen treffen und möglichst frei agieren kann sowie über finanzielle Mittel verfügt. Im Besten Falle ist das Klimaschutzmanagement als Stabsstelle organisiert, die Klimaschutzmanagerin ist also keine Sachbearbeiterin, die einer Fachdienstleitung unterstellt ist, sondern selber ein Fachdienst.",
                verbose_name="Gibt es ein Klimaschutzmanagement, das befugt ist, Entscheidungen zu treffen und über Haushaltsmittel verfügt?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_monitoring_exists",
            field=models.BooleanField(
                default=False,
                help_text="Monitoring bedeutet ein Überwachen/Überblick über den Erfolg von Klimaschutzmaßnahmen. In einem kommunalen Monitoring sollten die eingesparten Emissionen sichtbar gemacht werden und mit den Prognosen aus dem Klimaschutzkonzept verglichen werden. Falls die Kommune nicht im Zeitplan liegt: Wie soll nachgesteuert werden?\n\nDas Monitoring ist wichtig, um das Ziel der Klimaneutralität und notwendige Schritte im Auge zu behalten.",
                verbose_name="Gibt es ein Monitoring von Kimaschutzmaßnahmen?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_relevance_check_exists",
            field=models.BooleanField(
                default=False,
                help_text="Klimaschutz ist wichtig und muss als Querschnittsaufgabe umgesetzt werden. Alle Sachbearbeiterinnen, die Leitungsebene und auch die Politik muss – um Klimaneutralität zu erreichen – in allen Planungen Klimaschutz berücksichtigen!\n\nDaher ist es wesentlich, alle kommunalen Beschlüsse hinsichtlich ihrer Verträglichkeit mit Klimaschutz zu bewerten. Dies erfolgt durch eine Integration eines „Klima-Checks“/Klimarelevanzprüfung/Klimaschutzrelevanzprüfung in alle Beschlussvorlagen. Gesetzlich geregelt ist bisher nur, dass alle Beschlüsse auf ihre finanziellen Auswirkungen hin geprüft werden müssen. Unter jedem kommunalen Beschluss steht also ein kurzer Absatz über die Höhe der Kosten und eine Information,ob dies wiederkehrende Kosten sind.\n\nHier würden mit der Einführung einer Klimarelevanzprüfung weitere Informationen angefügt: Hat der Beschluss negative oder positive Auswirkungen auf den Klimaschutz, wurden Alternativen geprüft, warum wurden diese verworfen etc.\n\nBeschlüsse werden somit bereits während der Erstellung durch die Sachbearbeiter:innen in den Fachbereichen auf ihre Klimarelevanz hin (vor-)bewertet und Aspekte des Klimaschutzes sind automatisch integraler Bestandteil jeder Beschlussfassung. Klimafolgen werden somit transparent, Politiker:innen können fundierter entscheiden. Langfristig baut die Kommune Kompetenzen auf, um die Auswirkung auf das Klima bei allen relevanten Entscheidungen zu berücksichtigen.",
                verbose_name="Klimarelevanzprüfung: werden alle Beschlüsse von Verwaltung und Politik auf die Auswirkungen auf das Klima geprüft?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="intersectoral_concepts_exists",
            field=models.BooleanField(
                default=False,
                help_text="Sektorenübergreifende Konzepte sind zum Beispiel Kimaanpassungs- , Konzepte der Städtebauförderung oder Quartierskonzepte. Diese Konzepte betrachten Maßnahmen, die über mehrere Sektoren gehen, das Quartierskonzept betrachtet zum Beispiel die Gebäudesanierung, die Wärmeversorgung, Energieerzeugung und Aspekte der Stadtplanung.\n\nIn solchen Sektorenübergreifenden Konzepten, die neben dem Klimaschutzkonzept existieren ist es wichtig, das Kimaschutz eine zentrale Rolle spielt.",
                verbose_name="Beziehen (sektorenübergreifende) Konzepte und Planungspapiere die Klimaschutz mit ein?",
            ),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="public_relation_with_local_actors_exists",
            field=models.BooleanField(
                default=False,
                help_text="Mit Klimabeirat/Klimarat/Bürger:innenrat sind Gremien gemeint, die ausBürgerperspektive die Lokalpolitik beraten. Um politischen Einfluss auszuüben sollten diese regelmäßig tagen.",
                verbose_name="Gibt es einen Klimabeirat/Klimarat/Bürger:innenrat? Ist so ein Gremium in der Kommune eingerichtet und tagt regelmäßig?",
            ),
        ),
    ]
