# Generated by Django 4.2.7 on 2023-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0034_alter_administrationchecklist_climate_protection_management_exists_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="localgroup",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Ein Foto oder Logo der Lokalgruppe, mindestens 500 Pixel breit und 300 Pixel hoch.",
                upload_to="uploads/%Y/%m/%d/",
                verbose_name="Bild der Lokalgruppe",
            ),
        ),
    ]
