# Generated by Django 4.2.7 on 2023-11-24 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "cpmonitor",
            "0035_alter_localgroup_featured_image",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="inviter",
            ),
        ),
    ]
