# Generated by Django 4.1.7 on 2023-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0037_alter_administrationchecklist_intersectoral_concepts_exists_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="municipality_key",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Gemeindeschlüssel"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="show_roof_pv_indicator",
            field=models.BooleanField(
                default=False,
                help_text="\n            Graphik zur Entwicklung der Dach-PV anzeigen. Daten werden automatisch aus dem\n            Marktstammdatenregister bezogen. Der Gemeindeschlüssel muss dazu ausgefüllt sein.\n        ",
                verbose_name="Graphik Entwicklung Dach-PV",
            ),
        ),
    ]
