# Generated by Django 4.2.9 on 2024-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0038_energyplanchecklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyplanchecklist",
            name="communication_goals",
            field=models.BooleanField(
                default=False,
                verbose_name="Werden die Ergebnisse der Zielszenarien inkl. der Möglichkeit zur Kommentierung zugänglich gemacht? Gibt es eine Möglichkeit die Ergebnisse mit der Kommune zu diskutieren?",
            ),
        ),
        migrations.AddField(
            model_name="energyplanchecklist",
            name="communication_goals_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AddField(
            model_name="energyplanchecklist",
            name="communication_potential",
            field=models.BooleanField(
                default=False,
                verbose_name="Werden die Ergebnisse der Potenzialanalyse inkl. der Möglichkeit zur Kommentierung zugänglich gemacht? Gibt es eine Möglichkeit die Ergebnisse mit der Kommune zu diskutieren?",
            ),
        ),
        migrations.AddField(
            model_name="energyplanchecklist",
            name="communication_potential_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
    ]
