# Generated by Django 4.2.9 on 2024-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0039_energyplanchecklist_communication_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="communication_potential",
            field=models.BooleanField(
                default=False,
                help_text="Die Potenzialanalyse sollte inkl. der geplanten Maßnahmen öffentlich vorgestellt werden und zur Kommentierung offengelegt werden. Hier muss die Möglichkeit Feedback zu geben geschaffen werden, um ggf. die Potenzialanalyse noch anzupassen. Das ist wichtig, denn basierend auf der Potenzialanalyse wird das Zielszenario entwickelt.<br/>Gesetzlich vorgeschrieben ist lediglich die einmalige digitale Einsicht in die Pläne nach Erstellung des Entwurfs des Zielszenarios und der Einteilung in voraussichtliche Wärmeversorgunsgebiete inkl. Umsetzungsstrategie (§ 20 WPG, s.u.) für die Dauer von 30 Tagen zur Abgabe von Stellungnahmen.",
                verbose_name="Werden die Ergebnisse der Potenzialanalyse inkl. der Möglichkeit zur Kommentierung zugänglich gemacht? Gibt es eine Möglichkeit die Ergebnisse mit der Kommune zu diskutieren?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="demand_reduction_planned",
            field=models.BooleanField(
                default=False,
                help_text='<a target="blank" href="https://mitmachen-wiki.germanzero.org/w/LocalZero:Integration_betroffener_Sektoren">LocalZero Liste der betroffenen Sektoren</a>',
                verbose_name="Sind kommunale Maßnahmen zur Senkung des Wärmebedarfs enthalten (siehe sektorübergreifende Maßnahmen)?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="demand_specified",
            field=models.BooleanField(
                default=False,
                help_text='Sind alle oder zumindest die wichtigsten Bilanzen  und Kennzahlen der Gemeinde vorhanden?<br/>Wichtige Bilanzen:<ul><li>Energiebilanz</li><li>Treibhausgasbilanzen</li><li>räumlich aufgelöster Wärmebedarf</li></ul>Mögliche Kenngrößen:<ul><li>Wohnflächen</li><li>Nutzungsarten der Gebäude</li><li>Flächendichten</li><li>Gebäudetypen und Baualtersklassen</li><li>Versorgungs- und Beheizungsstruktur der Gebäude</li></ul><a target="_blank" href="https://www.kea-bw.de/waermewende/wissensportal/leistungsverzeichnis-kwp">Mehr Infos hier</a> (Leistungsverzeichnis A.1.1).',
                verbose_name="Ergibt sich ein klares gebäudescharfes Bild des Wärmebedarfs und der aktuellen Wärmeversorgungsart?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="effective_measures",
            field=models.BooleanField(
                default=False,
                help_text="<ul><li>Mit klaren Zuständigkeiten der beteiligten Akteure</li><li>Mit jahresscharfer Aktivität</li><li>Mit Fokus auf die wirksamsten Maßnahmen</li><li>Mit einem langfristigen Zeitplan, sodass die Gesamtheit der Maßnahmen im klimaneutralen Zieljahr abgeschlossen werden können (z.B. die lange dauernden Maßnahmen frühzeitig anschieben)</li></ul>",
                verbose_name="Entwickelt die Kommune (bzw. die von ihr beauftragten Akteure) einen aus den Potenzialen und Zielszenario abgeleiteten ambitionierten Transformationspfad mit effektiven Maßnahmen?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="energy_sources_sustainable",
            field=models.BooleanField(
                default=False,
                help_text="Auch hier kann die „Wasserstoff-Falle“ wieder zuschnappen. Denn viele Dekarbonisierungsstrategien z.B. von Stadtwerken basieren stark auf Wasserstoff. D.h. auch nach der Wärmeplanung ist es wichtig darauf zu achten, dass Wasserstoff weiter nicht im großen Stile eingesetzt werden soll (also z.B. als Energieträger in den Transformationsplänen der Stadtwerke).",
                verbose_name="Basieren die darauffolgend entwickelten Transformationspläne auf den von LocalZero empfohlenen Wärmequellen (und z.B. nicht wesentlich auf Wasserstoff oder Biomasse)?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="hydrogen_grid_examined",
            field=models.BooleanField(
                default=False,
                help_text="Ein potenzielles Wasserstoffgebiet kann hier bereits ausgeschlossen werden, wenn eine Eignung als sehr unwahrscheinlich eingestuft wird. Das ist zu dem Zeitpunkt der Wärmeplanung dann möglich, wenn entweder kein Gasnetz besteht oder bereits absehbar ist, dass eine künftige Versorgung mit Wasserstoff nicht wirtschaftlich sein wird. Disclaimer: Wasserstoffnetze sollten grundsätzlich ausgeschlossen werden: Verfügbarkeit und Kosten unsicher. Mit welcher Begründung geschieht dies vor Ort nicht?",
                verbose_name="Wurde ein frühzeitiger Ausschluss von Wasserstoffnetzen geprüft und das Ergebnis der Prüfung begründet?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="is_efficient",
            field=models.BooleanField(
                default=False,
                help_text='<a target="_blank" href="https://mitmachen-wiki.germanzero.org/w/LocalZero:Empfohlene_Erschlie%C3%9Fung_folgender_erneuerbarer_W%C3%A4rmequellen_und_%E2%80%93_speicher">LocalZero Liste der Wärmequellen</a>',
                verbose_name="Werden die möglichst effizienten und erneuerbaren Wärmequellen erschlossen?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="paris_agreement_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Damit wir in Deutschland dem Pariser Klimaabkommen entsprechen, müssen wir im Restbudget bleiben. Das bedeutet für jede Kommune:<ul><li>Wird ein möglichst 100% Anteil lokaler Erneuerbarer Energien zur Wärmeerzeugung erreicht?</li><li>Bis 2035?</li><li>Mit den von LocalZero empfohlenen Wärmeanwendungen?</li></ul>",
                verbose_name="Folgt das Zielszenario Paris-konformen Zielsetzungen und Grundsätzen der kommunalen Wärmeplanung?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="potential_determined",
            field=models.BooleanField(
                default=False,
                help_text='Es ist wichtig, dass sowohl umfangreich als auch priorisiert Wärmequellen berücksichtigt werden. <a target="_blank" href="https://mitmachen-wiki.germanzero.org/w/LocalZero:Empfohlene_Erschlie%C3%9Fung_folgender_erneuerbarer_W%C3%A4rmequellen_und_%E2%80%93_speicher">LocalZero Liste der empfohlenen Wärmequellen.</a>',
                verbose_name="Wurden alle sinnvollen Potenziale zur erneuerbaren Wärmeerzeugung und -speicherung erfasst?",
            ),
        ),
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="thermal_grid_examined",
            field=models.BooleanField(
                default=False,
                help_text="Ein potenzielles Wärmenetz kann hier bereits ausgeschlossen werden, wenn es entweder kein Wärmenetz gibt oder die Siedlungsstruktur (niedrige Wärmebedarfsdichte / hohe Zersiedelung) es nicht sinnvoll erscheinen lässt. Wenn Wärmenetze objektiv schlechte Lösungen sind, sollten sie frühzeitig ausgeschlossen werden um Planungskosten zu sparen und hohe Heizkosten am Ende des Tages zu vermeiden. Mit welcher Begründung geschieht dies vor Ort nicht?",
                verbose_name="Wurde ein frühzeitiger Ausschluss von Wärmenetzen geprüft und das Ergebnis der Prüfung begründet?",
            ),
        ),
    ]
