# Generated by Django 4.2.9 on 2024-03-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cpmonitor",
            "0040_alter_energyplanchecklist_communication_potential_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="supporting_ngos",
            field=models.TextField(
                blank=True,
                help_text="hier kann die Unterstüzung von anderen NGOs gewürdigt werden",
                verbose_name="Unterstützung von",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="supporting_ngos",
            field=models.TextField(
                blank=True,
                help_text="hier kann die Unterstüzung von anderen NGOs gewürdigt werden",
                verbose_name="Unterstützung von",
            ),
        ),
    ]
