# Generated by Django 4.2.9 on 2024-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0041_city_supporting_ngos_task_supporting_ngos"),
    ]

    operations = [
        migrations.AddField(
            model_name="localgroup",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="uploads/%Y/%m/%d/", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="localgroup",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Mindestens 500 Pixel breit und 300 Pixel hoch.",
                upload_to="uploads/%Y/%m/%d/",
                verbose_name="Bild der Lokalgruppe",
            ),
        ),
    ]
