# Generated by Django 4.2.9 on 2024-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0043_alter_administrationchecklist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_management_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_protection_monitoring_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="climate_relevance_check_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="guidelines_for_sustainable_procurement_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="intersectoral_concepts_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="municipal_office_for_funding_management_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="administrationchecklist",
            name="public_relation_with_local_actors_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_costs_are_specified_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="annual_reduction_of_emissions_can_be_predicted_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="based_on_remaining_co2_budget_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="cap_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="concept_for_participation_specified_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_business_as_usual_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="scenario_for_climate_neutrality_till_2035_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="sectors_of_climate_vision_used_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="target_date_exists_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_are_planned_yearly_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
        migrations.AlterField(
            model_name="capchecklist",
            name="tasks_have_responsible_entity_rationale",
            field=models.TextField(blank=True, verbose_name="Begründung"),
        ),
    ]
