# Generated by Django 4.2.9 on 2024-11-06 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0046_city_municipality_key_city_show_roof_pv_indicator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="localgroup",
            old_name="logo",
            new_name="logo_square",
        ),
    ]
