# Generated by Django 4.2.20 on 2026-01-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cpmonitor", "0048_localgroup_add_wide_logo_and_adjust_logo_help_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyplanchecklist",
            name="demand_specified",
            field=models.BooleanField(
                default=False,
                help_text='Sind alle oder zumindest die wichtigsten Bilanzen  und Kennzahlen der Gemeinde vorhanden?<br/>Wichtige Bilanzen:<ul><li>Energiebilanz</li><li>Treibhausgasbilanzen</li><li>räumlich aufgelöster Wärmebedarf</li></ul>Mögliche Kenngrößen:<ul><li>Wohnflächen</li><li>Nutzungsarten der Gebäude</li><li>Flächendichten</li><li>Gebäudetypen und Baualtersklassen</li><li>Versorgungs- und Beheizungsstruktur der Gebäude</li></ul><a target="_blank" href="https://www.kww-halle.de/service/infothek/detail/kww-musterleistungsverzeichnis-baden-wuerttemberg">Mehr Infos hier</a> (Leistungsverzeichnis A.1.1).',
                verbose_name="Ergibt sich ein klares gebäudescharfes Bild des Wärmebedarfs und der aktuellen Wärmeversorgungsart?",
            ),
        ),
    ]
