FROM dbeaver/cloudbeaver:23.0.2

ADD config/.cloudbeaver.runtime.conf /opt/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf
ADD config/initial-data-sources.conf /opt/cloudbeaver/conf/initial-data-sources.conf