FROM dbeaver/cloudbeaver:25.0.3

ADD config/.cloudbeaver.runtime.conf /opt/cloudbeaver/workspace/.data/.cloudbeaver.runtime.conf
ADD config/initial-data-sources.conf /opt/cloudbeaver/conf/initial-data-sources.conf