name: Climate plan monitor CI
on:
  push:
    branches:
      - 20-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build application
        run: docker compose --env-file .env.local up -d --build
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install pytest and playwright
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==1.3.2"
          poetry install --with dev
          poetry run playwright install --with-deps chromium
      - name: run tests
        run: poetry run pytest