name: Climate plan monitor CI
on:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.3.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install pytest and playwright
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ env.POETRY_VERSION }}
          poetry install --with dev
          poetry run playwright install --with-deps chromium
      - name: Run pre-commit hooks on all files
        run: SKIP=no-commit-to-branch poetry run pre-commit run --all-files
      - name: create database
        run: poetry run python manage.py migrate --settings=config.settings.local
      - name: fill database
        run: poetry run python manage.py loaddata --settings=config.settings.local e2e_tests/database/test_database.json
      - name: build testing application
        run: |
          sed -i 's/ENVIRONMENT_NAME=local/ENVIRONMENT_NAME=testing/g' .env
          docker-compose -f docker-compose.yml -p testing up -d
      - name: start reverse-proxy
        run: |
          cd docker/reverseproxy
          docker network create -d bridge production_nginx_network
          export CERTIFICATES_PATH=./ssl_certificates_localhost
          docker compose up -d --build
      - name: run tests
        run: poetry run pytest