name: Deploy
on:
  push:
    branches: [deploy-to-testing, deploy-to-production]
  workflow_dispatch:

jobs:
  get-environment:
    name: Get GitHub Environment
    # Determine the GitHub "Environment" to be used by the "deploy" job.
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine-environment.outputs.environment }}
      url:         ${{ steps.determine-environment.outputs.url }}
    steps:
      - id: determine-environment
        name: Determine environment
        run: |
          case $GITHUB_REF in
          refs/heads/deploy-to-production)
            echo "environment=production"
            echo "url=https://monitoring.localzero.net/"
            ;;
          refs/heads/deploy-to-testing)
            echo "environment=testing"
            echo "url=https://monitoring-test.localzero.net/"
            ;;
          *)
            echo "not an environment: $GITHUB_REF - should be refs/heads/deploy-to-{testing|production}"
            ;;
          esac >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ${{ needs.get-environment.outputs.environment }}
    runs-on: ubuntu-latest
    needs: get-environment
    environment:
      name: ${{ needs.get-environment.outputs.environment }}
      url:  ${{ needs.get-environment.outputs.url }}
    env:
      ENVIRONMENT: ${{ needs.get-environment.outputs.environment }}
      URL: ${{ needs.get-environment.outputs.url }}
      DIR: ${{ vars.DEPLOY_TO_DIR }} # Set here: https://github.com/GermanZero-de/klimaschutzmonitor/settings/variables/actions

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_lzm
          key: ${{ secrets.LZM_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.LZM_SSH_KNOWN_HOSTS }}
          config: |
            Host lzm
                HostName monitoring.localzero.net
                User monitoring
                IdentityFile ~/.ssh/id_lzm

      - name: Run deploy script
        shell: bash
        run: |
          chmod u+x deploy.sh
          ./deploy.sh "$ENVIRONMENT"
